// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BasicMaterialDocumentDataSlicesSlice = never;

/**
 * Content for Basic Material documents
 */
interface BasicMaterialDocumentData {
  /**
   * content field in *Basic Material*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_material.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Basic Material*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_material.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BasicMaterialDocumentDataSlicesSlice> /**
   * Meta Title field in *Basic Material*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: basic_material.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Basic Material*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: basic_material.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Basic Material*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_material.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Basic Material document from Prismic
 *
 * - **API ID**: `basic_material`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BasicMaterialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BasicMaterialDocumentData>,
    "basic_material",
    Lang
  >;

type OsnSdIpaDocumentDataSlicesSlice = never;

/**
 * Content for OSN SD IPA documents
 */
interface OsnSdIpaDocumentData {
  /**
   * content field in *OSN SD IPA*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sd_ipa.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SD IPA*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sd_ipa.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSdIpaDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SD IPA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sd_ipa.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SD IPA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sd_ipa.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SD IPA*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sd_ipa.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SD IPA document from Prismic
 *
 * - **API ID**: `osn_sd_ipa`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSdIpaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSdIpaDocumentData>,
    "osn_sd_ipa",
    Lang
  >;

type OsnSdMatematikaDocumentDataSlicesSlice = never;

/**
 * Content for OSN SD Matematika documents
 */
interface OsnSdMatematikaDocumentData {
  /**
   * content field in *OSN SD Matematika*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sd_matematika.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SD Matematika*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sd_matematika.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSdMatematikaDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SD Matematika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sd_matematika.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SD Matematika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sd_matematika.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SD Matematika*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sd_matematika.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SD Matematika document from Prismic
 *
 * - **API ID**: `osn_sd_matematika`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSdMatematikaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSdMatematikaDocumentData>,
    "osn_sd_matematika",
    Lang
  >;

type OsnSmaAstronomiDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Astronomi documents
 */
interface OsnSmaAstronomiDocumentData {
  /**
   * content field in *OSN SMA Astronomi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_astronomi.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Astronomi*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_astronomi.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaAstronomiDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Astronomi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_astronomi.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Astronomi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_astronomi.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Astronomi*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_astronomi.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Astronomi document from Prismic
 *
 * - **API ID**: `osn_sma_astronomi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaAstronomiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaAstronomiDocumentData>,
    "osn_sma_astronomi",
    Lang
  >;

type OsnSmaBiologiDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Biologi documents
 */
interface OsnSmaBiologiDocumentData {
  /**
   * content field in *OSN SMA Biologi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_biologi.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Biologi*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_biologi.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaBiologiDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Biologi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_biologi.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Biologi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_biologi.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Biologi*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_biologi.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Biologi document from Prismic
 *
 * - **API ID**: `osn_sma_biologi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaBiologiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaBiologiDocumentData>,
    "osn_sma_biologi",
    Lang
  >;

type OsnSmaEkonomiDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Ekonomi documents
 */
interface OsnSmaEkonomiDocumentData {
  /**
   * content field in *OSN SMA Ekonomi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_ekonomi.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Ekonomi*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_ekonomi.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaEkonomiDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Ekonomi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_ekonomi.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Ekonomi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_ekonomi.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Ekonomi*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_ekonomi.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Ekonomi document from Prismic
 *
 * - **API ID**: `osn_sma_ekonomi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaEkonomiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaEkonomiDocumentData>,
    "osn_sma_ekonomi",
    Lang
  >;

type OsnSmaFisikaDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Fisika documents
 */
interface OsnSmaFisikaDocumentData {
  /**
   * content field in *OSN SMA Fisika*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_fisika.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Fisika*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_fisika.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaFisikaDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Fisika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_fisika.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Fisika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_fisika.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Fisika*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_fisika.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Fisika document from Prismic
 *
 * - **API ID**: `osn_sma_fisika`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaFisikaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaFisikaDocumentData>,
    "osn_sma_fisika",
    Lang
  >;

type OsnSmaGeografiDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Geografi documents
 */
interface OsnSmaGeografiDocumentData {
  /**
   * content field in *OSN SMA Geografi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_geografi.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Geografi*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_geografi.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaGeografiDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Geografi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_geografi.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Geografi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_geografi.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Geografi*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_geografi.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Geografi document from Prismic
 *
 * - **API ID**: `osn_sma_geografi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaGeografiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaGeografiDocumentData>,
    "osn_sma_geografi",
    Lang
  >;

type OsnSmaInformatikaDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Informatika documents
 */
interface OsnSmaInformatikaDocumentData {
  /**
   * content field in *OSN SMA Informatika*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_informatika.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Informatika*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_informatika.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaInformatikaDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Informatika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_informatika.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Informatika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_informatika.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Informatika*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_informatika.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Informatika document from Prismic
 *
 * - **API ID**: `osn_sma_informatika`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaInformatikaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaInformatikaDocumentData>,
    "osn_sma_informatika",
    Lang
  >;

type OsnSmaKebumianDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Kebumian documents
 */
interface OsnSmaKebumianDocumentData {
  /**
   * content field in *OSN SMA Kebumian*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_kebumian.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Kebumian*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_kebumian.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaKebumianDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Kebumian*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_kebumian.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Kebumian*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_kebumian.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Kebumian*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_kebumian.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Kebumian document from Prismic
 *
 * - **API ID**: `osn_sma_kebumian`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaKebumianDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaKebumianDocumentData>,
    "osn_sma_kebumian",
    Lang
  >;

type OsnSmaKimiaDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMA Kimia documents
 */
interface OsnSmaKimiaDocumentData {
  /**
   * content field in *OSN SMA Kimia*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_kimia.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMA Kimia*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_kimia.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmaKimiaDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMA Kimia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_sma_kimia.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMA Kimia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_sma_kimia.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMA Kimia*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_sma_kimia.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMA Kimia document from Prismic
 *
 * - **API ID**: `osn_sma_kimia`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmaKimiaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmaKimiaDocumentData>,
    "osn_sma_kimia",
    Lang
  >;

type OsnSmpIpaDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMP IPA documents
 */
interface OsnSmpIpaDocumentData {
  /**
   * content field in *OSN SMP IPA*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_ipa.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMP IPA*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_ipa.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmpIpaDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMP IPA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_smp_ipa.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMP IPA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_smp_ipa.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMP IPA*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_ipa.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMP IPA document from Prismic
 *
 * - **API ID**: `osn_smp_ipa`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmpIpaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmpIpaDocumentData>,
    "osn_smp_ipa",
    Lang
  >;

type OsnSmpIpsDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMP IPS documents
 */
interface OsnSmpIpsDocumentData {
  /**
   * content field in *OSN SMP IPS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_ips.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMP IPS*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_ips.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmpIpsDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMP IPS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_smp_ips.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMP IPS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_smp_ips.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMP IPS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_ips.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMP IPS document from Prismic
 *
 * - **API ID**: `osn_smp_ips`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmpIpsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmpIpsDocumentData>,
    "osn_smp_ips",
    Lang
  >;

type OsnSmpMatematikaDocumentDataSlicesSlice = never;

/**
 * Content for OSN SMP Matematika documents
 */
interface OsnSmpMatematikaDocumentData {
  /**
   * content field in *OSN SMP Matematika*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_matematika.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *OSN SMP Matematika*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_matematika.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OsnSmpMatematikaDocumentDataSlicesSlice> /**
   * Meta Title field in *OSN SMP Matematika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: osn_smp_matematika.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OSN SMP Matematika*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: osn_smp_matematika.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OSN SMP Matematika*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: osn_smp_matematika.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OSN SMP Matematika document from Prismic
 *
 * - **API ID**: `osn_smp_matematika`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OsnSmpMatematikaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OsnSmpMatematikaDocumentData>,
    "osn_smp_matematika",
    Lang
  >;

export type AllDocumentTypes =
  | BasicMaterialDocument
  | OsnSdIpaDocument
  | OsnSdMatematikaDocument
  | OsnSmaAstronomiDocument
  | OsnSmaBiologiDocument
  | OsnSmaEkonomiDocument
  | OsnSmaFisikaDocument
  | OsnSmaGeografiDocument
  | OsnSmaInformatikaDocument
  | OsnSmaKebumianDocument
  | OsnSmaKimiaDocument
  | OsnSmpIpaDocument
  | OsnSmpIpsDocument
  | OsnSmpMatematikaDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BasicMaterialDocument,
      BasicMaterialDocumentData,
      BasicMaterialDocumentDataSlicesSlice,
      OsnSdIpaDocument,
      OsnSdIpaDocumentData,
      OsnSdIpaDocumentDataSlicesSlice,
      OsnSdMatematikaDocument,
      OsnSdMatematikaDocumentData,
      OsnSdMatematikaDocumentDataSlicesSlice,
      OsnSmaAstronomiDocument,
      OsnSmaAstronomiDocumentData,
      OsnSmaAstronomiDocumentDataSlicesSlice,
      OsnSmaBiologiDocument,
      OsnSmaBiologiDocumentData,
      OsnSmaBiologiDocumentDataSlicesSlice,
      OsnSmaEkonomiDocument,
      OsnSmaEkonomiDocumentData,
      OsnSmaEkonomiDocumentDataSlicesSlice,
      OsnSmaFisikaDocument,
      OsnSmaFisikaDocumentData,
      OsnSmaFisikaDocumentDataSlicesSlice,
      OsnSmaGeografiDocument,
      OsnSmaGeografiDocumentData,
      OsnSmaGeografiDocumentDataSlicesSlice,
      OsnSmaInformatikaDocument,
      OsnSmaInformatikaDocumentData,
      OsnSmaInformatikaDocumentDataSlicesSlice,
      OsnSmaKebumianDocument,
      OsnSmaKebumianDocumentData,
      OsnSmaKebumianDocumentDataSlicesSlice,
      OsnSmaKimiaDocument,
      OsnSmaKimiaDocumentData,
      OsnSmaKimiaDocumentDataSlicesSlice,
      OsnSmpIpaDocument,
      OsnSmpIpaDocumentData,
      OsnSmpIpaDocumentDataSlicesSlice,
      OsnSmpIpsDocument,
      OsnSmpIpsDocumentData,
      OsnSmpIpsDocumentDataSlicesSlice,
      OsnSmpMatematikaDocument,
      OsnSmpMatematikaDocumentData,
      OsnSmpMatematikaDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
